window.esdocSearchIndex = [
  [
    "pureimage/src/bitmap.js~bitmap",
    "class/src/bitmap.js~Bitmap.html",
    "<span>Bitmap</span> <span class=\"search-result-import-path\">pureimage/src/bitmap.js</span>",
    "class"
  ],
  [
    "pureimage/src/context.js~context",
    "class/src/context.js~Context.html",
    "<span>Context</span> <span class=\"search-result-import-path\">pureimage/src/context.js</span>",
    "class"
  ],
  [
    "pureimage/src/line.js~line",
    "class/src/Line.js~Line.html",
    "<span>Line</span> <span class=\"search-result-import-path\">pureimage/src/Line.js</span>",
    "class"
  ],
  [
    "pureimage/src/named_colors.js~named_colors",
    "variable/index.html#static-variable-NAMED_COLORS",
    "<span>NAMED_COLORS</span> <span class=\"search-result-import-path\">pureimage/src/named_colors.js</span>",
    "variable"
  ],
  [
    "pureimage/src/point.js~point",
    "class/src/Point.js~Point.html",
    "<span>Point</span> <span class=\"search-result-import-path\">pureimage/src/Point.js</span>",
    "class"
  ],
  [
    "pureimage/src/util.js~clamp",
    "function/index.html#static-function-clamp",
    "<span>clamp</span> <span class=\"search-result-import-path\">pureimage/src/util.js</span>",
    "function"
  ],
  [
    "pureimage/src/util.js~colorstringtouint32",
    "function/index.html#static-function-colorStringToUint32",
    "<span>colorStringToUint32</span> <span class=\"search-result-import-path\">pureimage/src/util.js</span>",
    "function"
  ],
  [
    "pureimage~decodejpegfromstream",
    "function/index.html#static-function-decodeJPEGFromStream",
    "<span>decodeJPEGFromStream</span> <span class=\"search-result-import-path\">pureimage</span>",
    "function"
  ],
  [
    "pureimage~decodepngfromstream",
    "function/index.html#static-function-decodePNGFromStream",
    "<span>decodePNGFromStream</span> <span class=\"search-result-import-path\">pureimage</span>",
    "function"
  ],
  [
    "pureimage~encodejpegtostream",
    "function/index.html#static-function-encodeJPEGToStream",
    "<span>encodeJPEGToStream</span> <span class=\"search-result-import-path\">pureimage</span>",
    "function"
  ],
  [
    "pureimage~encodepngtostream",
    "function/index.html#static-function-encodePNGToStream",
    "<span>encodePNGToStream</span> <span class=\"search-result-import-path\">pureimage</span>",
    "function"
  ],
  [
    "pureimage~make",
    "function/index.html#static-function-make",
    "<span>make</span> <span class=\"search-result-import-path\">pureimage</span>",
    "function"
  ],
  [
    "pureimage/src/text.js~measuretext",
    "function/index.html#static-function-measureText",
    "<span>measureText</span> <span class=\"search-result-import-path\">pureimage/src/text.js</span>",
    "function"
  ],
  [
    "pureimage/src/text.js~processtextpath",
    "function/index.html#static-function-processTextPath",
    "<span>processTextPath</span> <span class=\"search-result-import-path\">pureimage/src/text.js</span>",
    "function"
  ],
  [
    "pureimage/src/text.js~registerfont",
    "function/index.html#static-function-registerFont",
    "<span>registerFont</span> <span class=\"search-result-import-path\">pureimage/src/text.js</span>",
    "function"
  ],
  [
    "pureimage pureimage,pureimage",
    "test-file/specs/pureimage.test.js.html#lineNumber72",
    "JPEG image",
    "test"
  ],
  [
    "decodejpegfromstream src/pureimage.js~decodejpegfromstream,decodejpegfromstream",
    "test-file/specs/pureimage.test.js.html#lineNumber112",
    "JPEG image can be decoded from a stream",
    "test"
  ],
  [
    "encodejpegtostream src/pureimage.js~encodejpegtostream,encodejpegtostream",
    "test-file/specs/pureimage.test.js.html#lineNumber85",
    "JPEG image can be encoded to a stream",
    "test"
  ],
  [
    "encodejpegtostream src/pureimage.js~encodejpegtostream,encodejpegtostream",
    "test-file/specs/pureimage.test.js.html#lineNumber103",
    "JPEG image must be generated from a valid bitmap buffer",
    "test"
  ],
  [
    "line src/line.js~line,line",
    "test-file/specs/line.test.js.html#lineNumber7",
    "Line",
    "test"
  ],
  [
    "line#constructor src/line.js~line#constructor,line#constructor",
    "test-file/specs/line.test.js.html#lineNumber22",
    "Line can be created from 4 numbers and uses them as start and end points",
    "test"
  ],
  [
    "line#constructor src/line.js~line#constructor,line#constructor",
    "test-file/specs/line.test.js.html#lineNumber12",
    "Line can be created from two points and uses them as start and end points",
    "test"
  ],
  [
    "line#constructor src/line.js~line#constructor,line#constructor",
    "test-file/specs/line.test.js.html#lineNumber30",
    "Line can only be created with either 2 or 4 arguments",
    "test"
  ],
  [
    "line#constructor src/line.js~line#constructor,line#constructor",
    "test-file/specs/line.test.js.html#lineNumber42",
    "Line is the distance between two points",
    "test"
  ],
  [
    "pureimage pureimage,pureimage",
    "test-file/specs/pureimage.test.js.html#lineNumber10",
    "PNG image",
    "test"
  ],
  [
    "decodepngfromstream src/pureimage.js~decodepngfromstream,decodepngfromstream",
    "test-file/specs/pureimage.test.js.html#lineNumber50",
    "PNG image can be decoded from a stream",
    "test"
  ],
  [
    "encodepngtostream src/pureimage.js~encodepngtostream,encodepngtostream",
    "test-file/specs/pureimage.test.js.html#lineNumber23",
    "PNG image can be encoded to a stream",
    "test"
  ],
  [
    "encodepngtostream src/pureimage.js~encodepngtostream,encodepngtostream",
    "test-file/specs/pureimage.test.js.html#lineNumber41",
    "PNG image must be generated from a valid bitmap buffer",
    "test"
  ],
  [
    "point src/point.js~point,point",
    "test-file/specs/point.test.js.html#lineNumber6",
    "Point",
    "test"
  ],
  [
    "point#constructor src/point.js~point#constructor,point#constructor",
    "test-file/specs/point.test.js.html#lineNumber10",
    "Point represents a set of x and y co-ordinates in 2D space",
    "test"
  ],
  [
    "",
    "test-file/specs/path.test.js.html#lineNumber3",
    "draw curve",
    "test"
  ],
  [
    "",
    "test-file/specs/path.test.js.html#lineNumber61",
    "draw curve arc",
    "test"
  ],
  [
    "",
    "test-file/specs/path.test.js.html#lineNumber39",
    "draw curve bezier curve",
    "test"
  ],
  [
    "",
    "test-file/specs/path.test.js.html#lineNumber16",
    "draw curve canvas is empty and clear",
    "test"
  ],
  [
    "",
    "test-file/specs/path.test.js.html#lineNumber22",
    "draw curve making a square",
    "test"
  ],
  [
    "",
    "test-file/specs/path.test.js.html#lineNumber98",
    "draw curve north going polygon",
    "test"
  ],
  [
    "",
    "test-file/specs/path.test.js.html#lineNumber118",
    "draw curve transparent polygon",
    "test"
  ],
  [
    "",
    "test-file/specs/drawimage.test.js.html#lineNumber2",
    "drawImage",
    "test"
  ],
  [
    "",
    "test-file/specs/drawimage.test.js.html#lineNumber24",
    "drawImage can draw a full image",
    "test"
  ],
  [
    "",
    "test-file/specs/drawimage.test.js.html#lineNumber40",
    "drawImage can draw a plain image",
    "test"
  ],
  [
    "",
    "test-file/specs/drawimage.test.js.html#lineNumber47",
    "drawImage can draw a scaled image",
    "test"
  ],
  [
    "",
    "test-file/specs/drawimage.test.js.html#lineNumber31",
    "drawImage can stretch a full image",
    "test"
  ],
  [
    "",
    "test-file/specs/drawimage.test.js.html#lineNumber19",
    "drawImage canvas is empty and clear",
    "test"
  ],
  [
    "",
    "test-file/specs/gradientfill.test.js.html#lineNumber3",
    "drawing gradients",
    "test"
  ],
  [
    "",
    "test-file/specs/gradientfill.test.js.html#lineNumber18",
    "drawing gradients is making a linear gradient",
    "test"
  ],
  [
    "",
    "test-file/specs/gradientfill.test.js.html#lineNumber33",
    "drawing gradients is making a radial gradient",
    "test"
  ],
  [
    "specs/drawimage.test.js",
    "test-file/specs/drawimage.test.js.html",
    "specs/drawimage.test.js",
    "testFile"
  ],
  [
    "specs/gradientfill.test.js",
    "test-file/specs/gradientfill.test.js.html",
    "specs/gradientfill.test.js",
    "testFile"
  ],
  [
    "specs/line.test.js",
    "test-file/specs/line.test.js.html",
    "specs/line.test.js",
    "testFile"
  ],
  [
    "specs/path.test.js",
    "test-file/specs/path.test.js.html",
    "specs/path.test.js",
    "testFile"
  ],
  [
    "specs/point.test.js",
    "test-file/specs/point.test.js.html",
    "specs/point.test.js",
    "testFile"
  ],
  [
    "specs/pureimage.test.js",
    "test-file/specs/pureimage.test.js.html",
    "specs/pureimage.test.js",
    "testFile"
  ],
  [
    "specs/text.test.js",
    "test-file/specs/text.test.js.html",
    "specs/text.test.js",
    "testFile"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/gradient.js",
    "file/src/Gradient.js.html",
    "src/Gradient.js",
    "file"
  ],
  [
    "src/line.js",
    "file/src/Line.js.html",
    "src/Line.js",
    "file"
  ],
  [
    "src/line.js~line#constructor",
    "class/src/Line.js~Line.html#instance-constructor-constructor",
    "src/Line.js~Line#constructor",
    "method"
  ],
  [
    "src/line.js~line#end",
    "class/src/Line.js~Line.html#instance-member-end",
    "src/Line.js~Line#end",
    "member"
  ],
  [
    "src/line.js~line#getlength",
    "class/src/Line.js~Line.html#instance-method-getLength",
    "src/Line.js~Line#getLength",
    "method"
  ],
  [
    "src/line.js~line#start",
    "class/src/Line.js~Line.html#instance-member-start",
    "src/Line.js~Line#start",
    "member"
  ],
  [
    "src/point.js",
    "file/src/Point.js.html",
    "src/Point.js",
    "file"
  ],
  [
    "src/point.js~point#constructor",
    "class/src/Point.js~Point.html#instance-constructor-constructor",
    "src/Point.js~Point#constructor",
    "method"
  ],
  [
    "src/point.js~point#distance",
    "class/src/Point.js~Point.html#instance-method-distance",
    "src/Point.js~Point#distance",
    "method"
  ],
  [
    "src/point.js~point#divide",
    "class/src/Point.js~Point.html#instance-method-divide",
    "src/Point.js~Point#divide",
    "method"
  ],
  [
    "src/point.js~point#dotproduct",
    "class/src/Point.js~Point.html#instance-method-dotProduct",
    "src/Point.js~Point#dotProduct",
    "method"
  ],
  [
    "src/point.js~point#magnitude",
    "class/src/Point.js~Point.html#instance-method-magnitude",
    "src/Point.js~Point#magnitude",
    "method"
  ],
  [
    "src/point.js~point#subtract",
    "class/src/Point.js~Point.html#instance-method-subtract",
    "src/Point.js~Point#subtract",
    "method"
  ],
  [
    "src/point.js~point#x",
    "class/src/Point.js~Point.html#instance-member-x",
    "src/Point.js~Point#x",
    "member"
  ],
  [
    "src/point.js~point#y",
    "class/src/Point.js~Point.html#instance-member-y",
    "src/Point.js~Point#y",
    "member"
  ],
  [
    "src/bitmap.js",
    "file/src/bitmap.js.html",
    "src/bitmap.js",
    "file"
  ],
  [
    "src/bitmap.js~bitmap#calculateindex",
    "class/src/bitmap.js~Bitmap.html#instance-method-calculateIndex",
    "src/bitmap.js~Bitmap#calculateIndex",
    "method"
  ],
  [
    "src/bitmap.js~bitmap#constructor",
    "class/src/bitmap.js~Bitmap.html#instance-constructor-constructor",
    "src/bitmap.js~Bitmap#constructor",
    "method"
  ],
  [
    "src/bitmap.js~bitmap#data",
    "class/src/bitmap.js~Bitmap.html#instance-member-data",
    "src/bitmap.js~Bitmap#data",
    "member"
  ],
  [
    "src/bitmap.js~bitmap#getcontext",
    "class/src/bitmap.js~Bitmap.html#instance-method-getContext",
    "src/bitmap.js~Bitmap#getContext",
    "method"
  ],
  [
    "src/bitmap.js~bitmap#getpixelrgba",
    "class/src/bitmap.js~Bitmap.html#instance-method-getPixelRGBA",
    "src/bitmap.js~Bitmap#getPixelRGBA",
    "method"
  ],
  [
    "src/bitmap.js~bitmap#height",
    "class/src/bitmap.js~Bitmap.html#instance-member-height",
    "src/bitmap.js~Bitmap#height",
    "member"
  ],
  [
    "src/bitmap.js~bitmap#setpixelrgba",
    "class/src/bitmap.js~Bitmap.html#instance-method-setPixelRGBA",
    "src/bitmap.js~Bitmap#setPixelRGBA",
    "method"
  ],
  [
    "src/bitmap.js~bitmap#setpixelrgba_i",
    "class/src/bitmap.js~Bitmap.html#instance-method-setPixelRGBA_i",
    "src/bitmap.js~Bitmap#setPixelRGBA_i",
    "method"
  ],
  [
    "src/bitmap.js~bitmap#width",
    "class/src/bitmap.js~Bitmap.html#instance-member-width",
    "src/bitmap.js~Bitmap#width",
    "member"
  ],
  [
    "src/context.js",
    "file/src/context.js.html",
    "src/context.js",
    "file"
  ],
  [
    "src/context.js~context#arc",
    "class/src/context.js~Context.html#instance-method-arc",
    "src/context.js~Context#arc",
    "method"
  ],
  [
    "src/context.js~context#beginpath",
    "class/src/context.js~Context.html#instance-method-beginPath",
    "src/context.js~Context#beginPath",
    "method"
  ],
  [
    "src/context.js~context#beziercurveto",
    "class/src/context.js~Context.html#instance-method-bezierCurveTo",
    "src/context.js~Context#bezierCurveTo",
    "method"
  ],
  [
    "src/context.js~context#bitmap",
    "class/src/context.js~Context.html#instance-member-bitmap",
    "src/context.js~Context#bitmap",
    "member"
  ],
  [
    "src/context.js~context#clearrect",
    "class/src/context.js~Context.html#instance-method-clearRect",
    "src/context.js~Context#clearRect",
    "method"
  ],
  [
    "src/context.js~context#clip",
    "class/src/context.js~Context.html#instance-method-clip",
    "src/context.js~Context#clip",
    "method"
  ],
  [
    "src/context.js~context#closepath",
    "class/src/context.js~Context.html#instance-method-closePath",
    "src/context.js~Context#closePath",
    "method"
  ],
  [
    "src/context.js~context#constructor",
    "class/src/context.js~Context.html#instance-constructor-constructor",
    "src/context.js~Context#constructor",
    "method"
  ],
  [
    "src/context.js~context#createlineargradient",
    "class/src/context.js~Context.html#instance-method-createLinearGradient",
    "src/context.js~Context#createLinearGradient",
    "method"
  ],
  [
    "src/context.js~context#createradialgradient",
    "class/src/context.js~Context.html#instance-method-createRadialGradient",
    "src/context.js~Context#createRadialGradient",
    "method"
  ],
  [
    "src/context.js~context#drawimage",
    "class/src/context.js~Context.html#instance-method-drawImage",
    "src/context.js~Context#drawImage",
    "method"
  ],
  [
    "src/context.js~context#drawline",
    "class/src/context.js~Context.html#instance-method-drawLine",
    "src/context.js~Context#drawLine",
    "method"
  ],
  [
    "src/context.js~context#drawline_aa",
    "class/src/context.js~Context.html#instance-method-drawLine_aa",
    "src/context.js~Context#drawLine_aa",
    "method"
  ],
  [
    "src/context.js~context#drawline_noaa",
    "class/src/context.js~Context.html#instance-method-drawLine_noaa",
    "src/context.js~Context#drawLine_noaa",
    "method"
  ],
  [
    "src/context.js~context#fill",
    "class/src/context.js~Context.html#instance-method-fill",
    "src/context.js~Context#fill",
    "method"
  ],
  [
    "src/context.js~context#fillpixel",
    "class/src/context.js~Context.html#instance-method-fillPixel",
    "src/context.js~Context#fillPixel",
    "method"
  ],
  [
    "src/context.js~context#fillrect",
    "class/src/context.js~Context.html#instance-method-fillRect",
    "src/context.js~Context#fillRect",
    "method"
  ],
  [
    "src/context.js~context#fillstyle",
    "class/src/context.js~Context.html#instance-member-fillStyle",
    "src/context.js~Context#fillStyle",
    "member"
  ],
  [
    "src/context.js~context#filltext",
    "class/src/context.js~Context.html#instance-method-fillText",
    "src/context.js~Context#fillText",
    "method"
  ],
  [
    "src/context.js~context#fill_aa",
    "class/src/context.js~Context.html#instance-method-fill_aa",
    "src/context.js~Context#fill_aa",
    "method"
  ],
  [
    "src/context.js~context#fill_noaa",
    "class/src/context.js~Context.html#instance-method-fill_noaa",
    "src/context.js~Context#fill_noaa",
    "method"
  ],
  [
    "src/context.js~context#font",
    "class/src/context.js~Context.html#instance-member-font",
    "src/context.js~Context#font",
    "member"
  ],
  [
    "src/context.js~context#globalalpha",
    "class/src/context.js~Context.html#instance-member-globalAlpha",
    "src/context.js~Context#globalAlpha",
    "member"
  ],
  [
    "src/context.js~context#imagesmoothingenabled",
    "class/src/context.js~Context.html#instance-member-imageSmoothingEnabled",
    "src/context.js~Context#imageSmoothingEnabled",
    "member"
  ],
  [
    "src/context.js~context#lineto",
    "class/src/context.js~Context.html#instance-method-lineTo",
    "src/context.js~Context#lineTo",
    "method"
  ],
  [
    "src/context.js~context#linewidth",
    "class/src/context.js~Context.html#instance-member-lineWidth",
    "src/context.js~Context#lineWidth",
    "member"
  ],
  [
    "src/context.js~context#moveto",
    "class/src/context.js~Context.html#instance-method-moveTo",
    "src/context.js~Context#moveTo",
    "method"
  ],
  [
    "src/context.js~context#path",
    "class/src/context.js~Context.html#instance-member-path",
    "src/context.js~Context#path",
    "member"
  ],
  [
    "src/context.js~context#pathstart",
    "class/src/context.js~Context.html#instance-member-pathstart",
    "src/context.js~Context#pathstart",
    "member"
  ],
  [
    "src/context.js~context#pixelinsideclip",
    "class/src/context.js~Context.html#instance-method-pixelInsideClip",
    "src/context.js~Context#pixelInsideClip",
    "method"
  ],
  [
    "src/context.js~context#quadraticcurveto",
    "class/src/context.js~Context.html#instance-method-quadraticCurveTo",
    "src/context.js~Context#quadraticCurveTo",
    "method"
  ],
  [
    "src/context.js~context#restore",
    "class/src/context.js~Context.html#instance-method-restore",
    "src/context.js~Context#restore",
    "method"
  ],
  [
    "src/context.js~context#rotate",
    "class/src/context.js~Context.html#instance-method-rotate",
    "src/context.js~Context#rotate",
    "method"
  ],
  [
    "src/context.js~context#save",
    "class/src/context.js~Context.html#instance-method-save",
    "src/context.js~Context#save",
    "method"
  ],
  [
    "src/context.js~context#scale",
    "class/src/context.js~Context.html#instance-method-scale",
    "src/context.js~Context#scale",
    "method"
  ],
  [
    "src/context.js~context#stroke",
    "class/src/context.js~Context.html#instance-method-stroke",
    "src/context.js~Context#stroke",
    "method"
  ],
  [
    "src/context.js~context#strokepixel",
    "class/src/context.js~Context.html#instance-method-strokePixel",
    "src/context.js~Context#strokePixel",
    "method"
  ],
  [
    "src/context.js~context#strokerect",
    "class/src/context.js~Context.html#instance-method-strokeRect",
    "src/context.js~Context#strokeRect",
    "method"
  ],
  [
    "src/context.js~context#strokestyle",
    "class/src/context.js~Context.html#instance-member-strokeStyle",
    "src/context.js~Context#strokeStyle",
    "member"
  ],
  [
    "src/context.js~context#stroketext",
    "class/src/context.js~Context.html#instance-method-strokeText",
    "src/context.js~Context#strokeText",
    "method"
  ],
  [
    "src/context.js~context#textalign",
    "class/src/context.js~Context.html#instance-member-textAlign",
    "src/context.js~Context#textAlign",
    "member"
  ],
  [
    "src/context.js~context#textbaseline",
    "class/src/context.js~Context.html#instance-member-textBaseline",
    "src/context.js~Context#textBaseline",
    "member"
  ],
  [
    "src/context.js~context#transform",
    "class/src/context.js~Context.html#instance-member-transform",
    "src/context.js~Context#transform",
    "member"
  ],
  [
    "src/context.js~context#translate",
    "class/src/context.js~Context.html#instance-method-translate",
    "src/context.js~Context#translate",
    "method"
  ],
  [
    "src/context.js~context.colorstringtouint32",
    "class/src/context.js~Context.html#static-method-colorStringToUint32",
    "src/context.js~Context.colorStringToUint32",
    "method"
  ],
  [
    "src/named_colors.js",
    "file/src/named_colors.js.html",
    "src/named_colors.js",
    "file"
  ],
  [
    "src/pureimage.js",
    "file/src/pureimage.js.html",
    "src/pureimage.js",
    "file"
  ],
  [
    "src/text.js",
    "file/src/text.js.html",
    "src/text.js",
    "file"
  ],
  [
    "src/transform.js",
    "file/src/transform.js.html",
    "src/transform.js",
    "file"
  ],
  [
    "src/util.js",
    "file/src/util.js.html",
    "src/util.js",
    "file"
  ],
  [
    "",
    "test-file/specs/text.test.js.html#lineNumber5",
    "text drawing",
    "test"
  ],
  [
    "",
    "test-file/specs/text.test.js.html#lineNumber52",
    "text drawing can draw horizontal aligned text",
    "test"
  ],
  [
    "",
    "test-file/specs/text.test.js.html#lineNumber17",
    "text drawing can draw some text",
    "test"
  ],
  [
    "",
    "test-file/specs/text.test.js.html#lineNumber83",
    "text drawing can draw verticl aligned text",
    "test"
  ],
  [
    "",
    "test-file/specs/text.test.js.html#lineNumber30",
    "text drawing can measure text",
    "test"
  ]
]